### ISSUE TITLE
[FEAT]유저 프로필 작업

### ISSUE THREAD

**Issue by syhwang1231** [APPS-sookmyung/2023-COOKIEE-server#2]
## DESCRIPTION
특정 유저 프로필 조회 및 수정하기

## TODO
- [x] 유저 엔티티 개발
- [x] 조회, 수정 로직 개발
- [x] 에러 메시지 보내기
- [x] 테스트

## ETC
기타사항을 적어주세요(주의사항.. 등)
