### ISSUE TITLE
[FEAT] 카테고리 작업

### ISSUE THREAD

**Issue by syhwang1231** [APPS-sookmyung/2023-COOKIEE-server#9]
## DESCRIPTION
- 이벤트의 종류인 카테고리 등록, 조회, 수정, 삭제

## TODO
- [x] 카테고리 엔티티
- [x] 카테고리와 유저 엔티티 연관 관계... 제대로 되는지?
- [x] 카테고리 등록 기능
- [x] 카테고리 조회 기능
- [x] 카테고리 수정 기능
- [x] 카테고리 삭제 기능
- [x] 모든 기능 테스트하기

## ETC
- 카테고리 건드리기 전 유저와 관계 확인
